- name: Ensure systemd drop-in solr file doesn't exist
  file:
    path: /etc/systemd/system/solr.service.d/autorestart.conf
    state: absent
  register: solr_remove_autorestart_result

- name: Systemd daemon-reload
  systemd:
    name: solr
    daemon_reload: yes

- name: Solr restart
  systemd:
    name: solr
    state: restarted
  when: solr_remove_autorestart_result.changed and solr_restart_handler_enabled